-- Brava Materiais de Limpeza
-- Consolidação de produtos importados do relatório em variações/opções.
-- Execute uma vez no SQL Editor do Supabase depois de conferir o CSV de revisão.

begin;

with parent_source as (
  select *
  from (values
  ('amaciante-zavaski-coco-5-l', 'Amaciante Zavaski 5L', true),
  ('aromatizante-asa-140ml-floral-matricaria', 'Aromatizante ASA 140ml', true),
  ('aromatizante-cheirudo-140ml-bamboo', 'Aromatizante Cheirudo 140ml', true),
  ('aromatizante-coala-120ml-algas-marinhas', 'Aromatizante Coala 120ml', true),
  ('bloco-sanitario-p-caixa-acoplada-lavanda-higie-plus', 'Bloco Sanitário para Caixa Acoplada Higie Plus', true),
  ('bloqueador-sanitario-canela-premisse', 'Bloqueador Sanitário Premisse', true),
  ('cabo-aluminio-c-rosca-sanches-1-40mt-estriado', 'Cabo Alumínio com Rosca Sanches 1,40m', true),
  ('conjunto-mop-po-40cm-sanches', 'Conjunto Mop Pó Sanches', true),
  ('copo-180ml-dudigo-promo-com-25tr-transparente', 'Copo Descartável 180ml Transparente', true),
  ('copo-termico-brv-120ml-tira-c-25', 'Copo Térmico BRV', true),
  ('desinfetante-spry-concentrado-kaiaque-1-20', 'Desinfetante Spry Concentrado 1/20', true),
  ('detergente-clorado-zavaski-1l', 'Detergente Clorado Zavaski', true),
  ('fixar-aromatizantes-1l-spray-black', 'Fixar Aromatizantes 1L Spray', true),
  ('gel-adesivo-sanitario-sany-aplic-refil-lavanda-brv', 'Gel Adesivo Sanitário Sany Aplicador + Refil', true),
  ('luva-longatex-ranhurada-g', 'Luva Longatex Ranhurada', true),
  ('luva-latex-procedimento-bompack-g-c-100-c-po', 'Luva Látex Procedimento Bompack C/100 com Pó', true),
  ('luva-nitrilica-preta-g-c-100-bompack', 'Luva Nitrílica Preta Bompack C/100', true),
  ('luva-verniz-bompack-g-azul', 'Luva Verniz Bompack Azul', true),
  ('pano-multiuso-c-5un-vermelho-30x50cm', 'Pano Multiuso', true),
  ('pano-novo-microfibra-50x70-azul', 'Pano Novo Microfibra', true),
  ('pano-de-chao-alv-40x70', 'Pano de Chão', true),
  ('papel-hig-fofinho-folha-simples-30mt-pct-c4rl', 'Papel Higiênico Fofinho', true),
  ('papel-hig-rolao-branco-bv-c-8', 'Papel Higiênico Rolão', true),
  ('refil-mop-po-40-sanches', 'Refil Mop Pó Sanches', true),
  ('refil-sabonete-liq-proteinas-do-leite-spray-400ml-trilha', 'Refil Sabonete Líquido Proteínas do Leite Spray Trilha', true),
  ('refil-alcool-70-spray-400ml-trilha', 'Refil Álcool 70% Spray Trilha', true),
  ('rodo-aluminio-reforcado-sanches-40cm-c-cabo-aluminio-de-1-50-mt-rosca', 'Rodo Alumínio Reforçado Sanches com Cabo', true),
  ('rodo-plastico-40cm-sanches', 'Rodo Plástico Sanches', true),
  ('sabonete-liquido-ameixa-dourada-coala-500ml-pump', 'Sabonete Líquido Coala 500ml Pump', true),
  ('sabonete-liq-premisse-algas-marinhas-5l', 'Sabonete Líquido Premisse 5L', true),
  ('sabonete-liq-sebold-cha-branco-5l', 'Sabonete Líquido Sebold 5L', true),
  ('saboneteira-trilha-crem-c-reserv-branco', 'Saboneteira Trilha Crem com Reservatório', true),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'Sacos de Lixo', false),
  ('suporte-rolao-crem-600m-trilha-branco', 'Suporte Rolão Crem 600m Trilha', true),
  ('vassoura-novica-original-sem-cabo', 'Vassoura Noviça Original', true),
  ('agua-perfumada-caszulo-bambu-orieltal-500ml', 'Água Perfumada Caszulo 500ml', true),
  ('alcool-acendedor-araras-5l-80', 'Álcool Acendedor 5L 80%', true),
  ('alcool-liquido-70-1-l-araras', 'Álcool Líquido Araras 70%', true),
  ('alcool-liquido-70-1-l-vale-verde', 'Álcool Líquido Vale Verde 1L', true),
  ('alcool-perfumado-floral-quimak-5l', 'Álcool Perfumado Quimak 5L', true)
  ) as v(parent_slug, base_name, parent_is_member)
)
update public.products p
set
  name = ps.base_name,
  code = case when ps.parent_is_member then null else p.code end,
  description = case
    when ps.parent_is_member then 'Produto com opções de tamanho, fragrância, cor ou modelo. Selecione a opção desejada e solicite orçamento pelo WhatsApp.'
    else p.description
  end
from parent_source ps
where p.slug = ps.parent_slug;

with variant_source as (
  select *
  from (values
  ('amaciante-zavaski-coco-5-l', 'amaciante-zavaski-coco-5-l', 'Coco', '6669', 'Amaciante Zavaski Coco 5 L', 1),
  ('amaciante-zavaski-coco-5-l', 'amaciante-zavaski-lavanda-5-l', 'Lavanda', '6670', 'Amaciante Zavaski Lavanda 5 L', 2),
  ('aromatizante-asa-140ml-floral-matricaria', 'aromatizante-asa-140ml-floral-matricaria', 'Floral Matricaria', '4324', 'Aromatizante ASA 140ML Floral Matricaria', 1),
  ('aromatizante-asa-140ml-floral-matricaria', 'aromatizante-asa-140ml-laranja-c-canela', 'Laranja c Canela', '4348', 'Aromatizante ASA 140ML Laranja C/ Canela', 2),
  ('aromatizante-cheirudo-140ml-bamboo', 'aromatizante-cheirudo-140ml-bamboo', 'Bamboo', '8862', 'Aromatizante Cheirudo 140ML Bamboo', 1),
  ('aromatizante-cheirudo-140ml-bamboo', 'aromatizante-cheirudo-140ml-lavanda', 'Lavanda', '4279', 'Aromatizante Cheirudo 140ML Lavanda', 2),
  ('aromatizante-cheirudo-140ml-bamboo', 'aromatizante-cheirudo-140ml-talco', 'Talco', '4325', 'Aromatizante Cheirudo 140ML Talco', 3),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-algas-marinhas', 'Algas Marinhas', '7756', 'Aromatizante Coala 120ML Algas Marinhas', 1),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-algodao', 'Algodão', '7840', 'Aromatizante Coala 120ML Algodao', 2),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-bambu', 'Bambu', '7757', 'Aromatizante Coala 120ML Bambu', 3),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-cha-branco', 'Chá Branco', '7758', 'Aromatizante Coala 120ML CHA Branco', 4),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-cravo-e-canela', 'Cravo e Canela', '7850', 'Aromatizante Coala 120ML Cravo e Canela', 5),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-eucalipto', 'Eucalipto', '7851', 'Aromatizante Coala 120ML Eucalipto', 6),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-lavanda', 'Lavanda', '7802', 'Aromatizante Coala 120ML Lavanda', 7),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-lima-limao', 'Lima Limão', '7759', 'Aromatizante Coala 120ML Lima Limao', 8),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-orquidea-negra', 'Orquídea Negra', '7760', 'Aromatizante Coala 120ML Orquidea Negra', 9),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-pinho', 'Pinho', '7803', 'Aromatizante Coala 120ML Pinho', 10),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizante-coala-120ml-talco', 'Talco', '7761', 'Aromatizante Coala 120ML Talco', 11),
  ('bloco-sanitario-p-caixa-acoplada-lavanda-higie-plus', 'bloco-sanitario-p-caixa-acoplada-lavanda-higie-plus', 'Lavanda', '9880', 'Bloco Sanitário P/ Caixa Acoplada Lavanda Higie Plus', 1),
  ('bloco-sanitario-p-caixa-acoplada-lavanda-higie-plus', 'bloco-sanitario-p-caixa-acoplada-marine-higie-plus', 'Marine', '9881', 'Bloco Sanitário P/ Caixa Acoplada Marine Higie Plus', 2),
  ('bloqueador-sanitario-canela-premisse', 'bloqueador-sanitario-canela-premisse', 'Canela', '5546', 'Bloqueador Sanitário Canela Premisse', 1),
  ('bloqueador-sanitario-canela-premisse', 'bloqueador-sanitario-capim-limao-premisse', 'Capim Limão', '7769', 'Bloqueador Sanitário Capim Limao Premisse', 2),
  ('bloqueador-sanitario-canela-premisse', 'bloqueador-sanitario-tutti-frutti-premisse', 'Tutti Frutti', '5547', 'Bloqueador Sanitário Tutti Frutti Premisse', 3),
  ('cabo-aluminio-c-rosca-sanches-1-40mt-estriado', 'cabo-aluminio-c-rosca-sanches-1-40mt-estriado', 'Estriado', '6682', 'Cabo Aluminio C/rosca Sanches 1,40MT Estriado', 1),
  ('cabo-aluminio-c-rosca-sanches-1-40mt-estriado', 'cabo-aluminio-c-rosca-sanches-1-40mt-liso', 'Liso', '5484', 'Cabo Aluminio C/rosca Sanches 1,40MT Liso', 2),
  ('conjunto-mop-po-40cm-sanches', 'conjunto-mop-po-40cm-sanches', '40CM', '6683', 'Conjunto MOP PÓ 40CM Sanches', 1),
  ('conjunto-mop-po-40cm-sanches', 'conjunto-mop-po-60cm-sanches', '60CM', '5488', 'Conjunto MOP PÓ 60CM Sanches', 2),
  ('copo-180ml-dudigo-promo-com-25tr-transparente', 'copo-180ml-dudigo-promo-com-25tr-transparente', 'Dudigo Promo com 25TR', '7831', 'Copo 180ML Dudigo Promo com 25TR Transparente', 1),
  ('copo-180ml-dudigo-promo-com-25tr-transparente', 'copo-180ml-dudigo-tr-c-100-transparente', 'Dudigo TR c 100', '66', 'Copo 180ML Dudigo TR C/100 Transparente', 2),
  ('copo-180ml-dudigo-promo-com-25tr-transparente', 'copo-180ml-gpack-glight-com-25tr-transparente', 'Gpack Glight com 25TR', '9914', 'Copo 180ML Gpack Glight com 25TR Transparente', 3),
  ('copo-180ml-dudigo-promo-com-25tr-transparente', 'copo-180ml-gpack-com-25tr-transparente', 'Gpack com 25TR', '9913', 'Copo 180ML Gpack com 25TR Transparente', 4),
  ('copo-termico-brv-120ml-tira-c-25', 'copo-termico-brv-120ml-tira-c-25', '120ML Tira c 25', '85', 'Copo Termico BRV 120ML Tira C/25', 1),
  ('copo-termico-brv-120ml-tira-c-25', 'copo-termico-brv-180ml-tira-c-25', '180ML Tira c 25', '86', 'Copo Termico BRV 180ML Tira C/25', 2),
  ('desinfetante-spry-concentrado-kaiaque-1-20', 'desinfetante-spry-concentrado-kaiaque-1-20', 'Kaiaque', '6644', 'Desinfetante Spry Concentrado Kaiaque 1/20', 1),
  ('desinfetante-spry-concentrado-kaiaque-1-20', 'desinfetante-spry-concentrado-lavanda-1-20', 'Lavanda', '6657', 'Desinfetante Spry Concentrado Lavanda 1/20', 2),
  ('desinfetante-spry-concentrado-kaiaque-1-20', 'desinfetante-spry-concentrado-marine-1-20', 'Marine', '7748', 'Desinfetante Spry Concentrado Marine 1/20', 3),
  ('desinfetante-spry-concentrado-kaiaque-1-20', 'desinfetante-spry-concentrado-talco-1-20', 'Talco', '6661', 'Desinfetante Spry Concentrado Talco 1/20', 4),
  ('detergente-clorado-zavaski-1l', 'detergente-clorado-zavaski-1l', '1L', '5541', 'Detergente Clorado Zavaski 1L', 1),
  ('detergente-clorado-zavaski-1l', 'detergente-clorado-zavaski-5l', '5L', '6671', 'Detergente Clorado Zavaski 5L', 2),
  ('fixar-aromatizantes-1l-spray-black', 'fixar-aromatizantes-1l-spray-black', 'Black', '7854', 'Fixar Aromatizantes 1L Spray Black', 1),
  ('fixar-aromatizantes-1l-spray-black', 'fixar-aromatizantes-1l-spray-vanilla', 'Vanilla', '7857', 'Fixar Aromatizantes 1L Spray Vanilla', 2),
  ('gel-adesivo-sanitario-sany-aplic-refil-lavanda-brv', 'gel-adesivo-sanitario-sany-aplic-refil-lavanda-brv', 'Lavanda', '1798', 'GEL Adesivo Sanitário Sany Aplic+refil Lavanda BRV', 1),
  ('gel-adesivo-sanitario-sany-aplic-refil-lavanda-brv', 'gel-adesivo-sanitario-sany-aplic-refil-marine-brv', 'Marine', '1799', 'GEL Adesivo Sanitário Sany Aplic+refil Marine BRV', 2),
  ('luva-longatex-ranhurada-g', 'luva-longatex-ranhurada-g', 'G', '6614', 'Luva Longatex/ranhurada G', 1),
  ('luva-longatex-ranhurada-g', 'luva-longatex-ranhurada-m', 'M', '727', 'Luva Longatex/ranhurada M', 2),
  ('luva-latex-procedimento-bompack-g-c-100-c-po', 'luva-latex-procedimento-bompack-g-c-100-c-po', 'G', '5474', 'Luva Latex Procedimento Bompack G C/100 C/pó', 1),
  ('luva-latex-procedimento-bompack-g-c-100-c-po', 'luva-latex-procedimento-bompack-m-c-100-c-po', 'M', '5475', 'Luva Latex Procedimento Bompack M C/100 C/pó', 2),
  ('luva-latex-procedimento-bompack-g-c-100-c-po', 'luva-latex-procedimento-bompack-p-c-100-c-po', 'P', '5476', 'Luva Latex Procedimento Bompack P C/100 C/pó', 3),
  ('luva-latex-procedimento-bompack-g-c-100-c-po', 'luva-latex-procedimento-bompack-pp-c-100-c-po', 'PP', '6658', 'Luva Latex Procedimento Bompack PP C/100 C/pó', 4),
  ('luva-nitrilica-preta-g-c-100-bompack', 'luva-nitrilica-preta-g-c-100-bompack', 'G', '4412', 'Luva Nitrilica Preta G C/100 Bompack', 1),
  ('luva-nitrilica-preta-g-c-100-bompack', 'luva-nitrilica-preta-g-g-c-100-bompack', 'GG', '5577', 'Luva Nitrilica Preta G G C/100 Bompack', 2),
  ('luva-nitrilica-preta-g-c-100-bompack', 'luva-nitrilica-preta-m-c-100-bompack', 'M', '4411', 'Luva Nitrilica Preta M C/100 Bompack', 3),
  ('luva-nitrilica-preta-g-c-100-bompack', 'luva-nitrilica-preta-p-c-100-bompack', 'P', '4410', 'Luva Nitrilica Preta P C/100 Bompack', 4),
  ('luva-verniz-bompack-g-azul', 'luva-verniz-bompack-g-azul', 'G', '739', 'Luva Verniz Bompack G Azul', 1),
  ('luva-verniz-bompack-g-azul', 'luva-verniz-bompack-m-azul', 'M', '736', 'Luva Verniz Bompack M Azul', 2),
  ('luva-verniz-bompack-g-azul', 'luva-verniz-bompack-p-azul', 'P', '742', 'Luva Verniz Bompack P Azul', 3),
  ('pano-multiuso-c-5un-vermelho-30x50cm', 'pano-multiuso-c-5un-vermelho-30x50cm', 'c 5UN Vermelho 30X50CM', '4370', 'Pano Multiuso C/ 5UN Vermelho 30X50CM', 1),
  ('pano-multiuso-c-5un-vermelho-30x50cm', 'pano-multiuso-rolo-30x30m-azul-rende-50-panos', 'Rolo 30X30M Azul Rende 50 Panos', '647', 'Pano Multiuso Rolo 30X30M Azul - Rende 50 Panos', 2),
  ('pano-multiuso-c-5un-vermelho-30x50cm', 'pano-multiuso-rolo-30x30m-verde-rende-50-panos', 'Rolo 30X30M Verde Rende 50 Panos', '649', 'Pano Multiuso Rolo 30X30M Verde - Rende 50 Panos', 3),
  ('pano-multiuso-c-5un-vermelho-30x50cm', 'pano-multiuso-rolo-bompack-azul-rende-600panos', 'Rolo Bompack Azul Rende 600PANOS', '650', 'Pano Multiuso Rolo Bompack Azul - Rende 600PANOS', 4),
  ('pano-novo-microfibra-50x70-azul', 'pano-novo-microfibra-50x70-azul', '50X70 Azul', '638', 'Pano Novo Microfibra 50X70 Azul', 1),
  ('pano-novo-microfibra-50x70-azul', 'pano-novo-microfibra-50x70-verde', '50X70 Verde', '6602', 'Pano Novo Microfibra 50X70 Verde', 2),
  ('pano-novo-microfibra-50x70-azul', 'pano-novo-microfibra-azul-peq-39x39cm', 'Azul PEQ 39X39CM', '640', 'Pano Novo Microfibra Azul Peq. 39X39CM', 3),
  ('pano-novo-microfibra-50x70-azul', 'pano-novo-microfibra-grande-39x59cm-azul', 'Grande 39X59CM Azul', '639', 'Pano Novo Microfibra Grande 39X59CM Azul', 4),
  ('pano-novo-microfibra-50x70-azul', 'pano-novo-microfibra-verde-peq-39x39cm', 'Verde PEQ 39X39CM', '9888', 'Pano Novo Microfibra Verde Peq. 39X39CM', 5),
  ('pano-de-chao-alv-40x70', 'pano-de-chao-alv-40x70', 'ALV 40X70', '629', 'Pano de Chao Alv. 40X70', 1),
  ('pano-de-chao-alv-40x70', 'pano-de-chao-saco-economico-35x60-liso', 'Saco Economico 35X60 Liso', '634', 'Pano de Chao Saco Economico 35X60 Liso', 2),
  ('pano-de-chao-alv-40x70', 'pano-de-chao-xadrez-extra-40x70', 'Xadrez Extra 40X70', '4393', 'Pano de Chao Xadrez Extra 40X70', 3),
  ('papel-hig-fofinho-folha-simples-30mt-pct-c4rl', 'papel-hig-fofinho-folha-simples-30mt-pct-c4rl', 'Folha Simples 30MT PCT C4RL', '3243', 'Papel HIG Fofinho Folha Simples 30MT PCT C4RL', 1),
  ('papel-hig-fofinho-folha-simples-30mt-pct-c4rl', 'papel-hig-30m-f-dupla-fofinho-pc-c-04rolos', '30M F Dupla PC c 04ROLOS', '42', 'Papel Hig. 30M F.dupla Fofinho PC C/04ROLOS', 2),
  ('papel-hig-fofinho-folha-simples-30mt-pct-c4rl', 'papel-hig-30m-fofinho-f-dupla-pc-c-12-rolos', 'F Dupla PC c 12 Rolos', '47', 'Papel Hig. 30M Fofinho F.dupla PC C/12 Rolos', 3),
  ('papel-hig-fofinho-folha-simples-30mt-pct-c4rl', 'papel-hig-60m-f-simples-fofinho-pc-c-04-rolos', '60M F Simples PC c 04 Rolos', '53', 'Papel Hig. 60M F.simples Fofinho PC C/04 Rolos', 4),
  ('papel-hig-rolao-branco-bv-c-8', 'papel-hig-rolao-branco-bv-c-8', 'Branco BV c 8', '4331', 'Papel Hig. Rolao Branco BV C/8', 1),
  ('papel-hig-rolao-branco-bv-c-8', 'papel-hig-rolao-extra-luxo-bv-fd-c-8-rolos-300mt', 'Extra Luxo BV FD c 8 Rolos 300MT', '4292', 'Papel Hig. Rolao Extra Luxo BV FD C/ 8 Rolos 300MT', 2),
  ('papel-hig-rolao-branco-bv-c-8', 'papel-hig-rolao-folha-dupla-ipel-200mt-8-rolos', 'Folha Dupla Ipel 200MT 8 Rolos', '7736', 'Papel Hig. Rolao Folha Dupla Ipel 200MT 8 Rolos', 3),
  ('papel-hig-rolao-branco-bv-c-8', 'papel-hig-rolao-plus-bv-c-8', 'Plus BV c 8', '4358', 'Papel Hig. Rolao Plus BV C/8', 4),
  ('refil-mop-po-40-sanches', 'refil-mop-po-40-sanches', '40', '5516', 'Refil MOP PÓ 40 Sanches', 1),
  ('refil-mop-po-40-sanches', 'refil-mop-po-60-sanches', '60', '5509', 'Refil MOP PÓ 60 Sanches', 2),
  ('refil-mop-po-40-sanches', 'refil-mop-po-80-sanches', '80', '1850', 'Refil MOP PÓ 80 Sanches', 3),
  ('refil-sabonete-liq-proteinas-do-leite-spray-400ml-trilha', 'refil-sabonete-liq-proteinas-do-leite-spray-400ml-trilha', '400ML', '4433', 'Refil Sabonete LIQ Proteinas do Leite Spray 400ML Trilha', 1),
  ('refil-sabonete-liq-proteinas-do-leite-spray-400ml-trilha', 'refil-sabonete-liq-proteinas-do-leite-spray-800ml-trilha', '800ML', '4342', 'Refil Sabonete LIQ Proteinas do Leite Spray 800ML Trilha', 2),
  ('refil-alcool-70-spray-400ml-trilha', 'refil-alcool-70-spray-400ml-trilha', '400ML', '4429', 'Refil Alcool 70% Spray 400ML Trilha', 1),
  ('refil-alcool-70-spray-400ml-trilha', 'refil-alcool-70-spray-800ml-trilha', '800ML', '4428', 'Refil Alcool 70% Spray 800ML Trilha', 2),
  ('rodo-aluminio-reforcado-sanches-40cm-c-cabo-aluminio-de-1-50-mt-rosca', 'rodo-aluminio-reforcado-sanches-40cm-c-cabo-aluminio-de-1-50-mt-rosca', '40CM', '1718', 'Rodo Aluminio Reforçado Sanches 40CM C/cabo Aluminio de 1,50 MT Rosca -', 1),
  ('rodo-aluminio-reforcado-sanches-40cm-c-cabo-aluminio-de-1-50-mt-rosca', 'rodo-aluminio-reforcado-sanches-60cm-c-cabo-aluminio-1-50-mt-rosca', '60CM', '1719', 'Rodo Aluminio Reforçado Sanches 60CM C/cabo Aluminio 1,50 MT Rosca', 2),
  ('rodo-plastico-40cm-sanches', 'rodo-plastico-40cm-sanches', '40CM', '1737', 'Rodo Plastico 40CM Sanches', 1),
  ('rodo-plastico-40cm-sanches', 'rodo-plastico-60cm-sanches', '60CM', '1738', 'Rodo Plastico 60CM Sanches', 2),
  ('sabonete-liquido-ameixa-dourada-coala-500ml-pump', 'sabonete-liquido-ameixa-dourada-coala-500ml-pump', 'Ameixa Dourada', '9895', 'Sabonete Liquido Ameixa Dourada Coala 500ML Pump', 1),
  ('sabonete-liquido-ameixa-dourada-coala-500ml-pump', 'sabonete-liquido-flor-de-figo-coala-500ml-pump', 'Flor de Figo', '9886', 'Sabonete Liquido Flor de Figo Coala 500ML Pump', 2),
  ('sabonete-liquido-ameixa-dourada-coala-500ml-pump', 'sabonete-liquido-orquidea-negra-coala-500ml-pump', 'Orquídea Negra', '7838', 'Sabonete Liquido Orquidea Negra Coala 500ML Pump', 3),
  ('sabonete-liq-premisse-algas-marinhas-5l', 'sabonete-liq-premisse-algas-marinhas-5l', 'Algas Marinhas', '6664', 'Sabonete LIQ Premisse Algas Marinhas 5L', 1),
  ('sabonete-liq-premisse-algas-marinhas-5l', 'sabonete-liq-premisse-morango-e-champagne-5l', 'Morango e Champagne', '7810', 'Sabonete LIQ Premisse Morango e Champagne 5L', 2),
  ('sabonete-liq-sebold-cha-branco-5l', 'sabonete-liq-sebold-cha-branco-5l', 'Chá Branco', '7765', 'Sabonete LIQ Sebold CHA Branco 5L', 1),
  ('sabonete-liq-sebold-cha-branco-5l', 'sabonete-liq-sebold-erva-doce-5l', 'Erva Doce', '7703', 'Sabonete LIQ Sebold Erva Doce 5L', 2),
  ('sabonete-liq-sebold-cha-branco-5l', 'sabonete-liq-sebold-pessego-5l', 'Pessego', '6701', 'Sabonete LIQ Sebold Pessego 5L', 3),
  ('saboneteira-trilha-crem-c-reserv-branco', 'saboneteira-trilha-crem-c-reserv-branco', 'Branco', '4427', 'Saboneteira Trilha Crem C Reserv Branco', 1),
  ('saboneteira-trilha-crem-c-reserv-branco', 'saboneteira-trilha-crem-c-reserv-preto', 'Preto', '4318', 'Saboneteira Trilha Crem C Reserv Preto', 2),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-100l-0-20mc-preto-pc-c-50un', '100L 0 20MC Preto PC c 50UN', '91', 'Saco de Lixo 100L 0,20MC Preto PC C/50UN', 1),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-100l-0-5-mc-preto-75x90cm-c-100', '100L 0 5 MC Preto 75X90CM c 100', '92', 'Saco de Lixo 100L 0,5 MC Preto 75X90CM C/100', 2),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-100l-ref-0-10-mc-preto-c-100', '100L REF 0 10 MC Preto c 100', '93', 'Saco de Lixo 100L Ref. 0,10 MC Preto C/100', 3),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-100l-ref-0-12-mc-preto-c-100', '100L REF 0 12 MC Preto c 100', '94', 'Saco de Lixo 100L Ref. 0,12 MC Preto C/100', 4),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-100l-ref-0-8-mc-preto-c-100', '100L REF 0 8 MC Preto c 100', '95', 'Saco de Lixo 100L Ref. 0,8 MC Preto C/100', 5),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-150l-ref-0-10mc-90x105cm-c-100', '150L REF 0 10MC 90X105CM c 100', '97', 'Saco de Lixo 150L REF.0,10MC - 90X105CM C/100', 6),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-150l-ref-0-12-mc-preto-c-100', '150L REF 0 12 MC Preto c 100', '96', 'Saco de Lixo 150L Ref. 0,12 MC Preto C/100', 7),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-200l-0-12-preto-c-100', '200L 0 12 Preto c 100', '106', 'Saco de Lixo 200L 0,12 Preto C/100', 8),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-200l-0-20-c-50', '200L 0 20 c 50', '107', 'Saco de Lixo 200L 0,20 C/50', 9),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-20l-0-04-mc-preto-40x50cm-c-100', '20L 0 04 MC Preto 40X50CM c 100', '109', 'Saco de Lixo 20L 0,04 MC Preto 40X50CM C/100', 10),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-20l-ref-mc-preto-40x50cm-c-100', '20L REF MC Preto 40X50CM c 100', '4407', 'Saco de Lixo 20L REF MC Preto 40X50CM C/100', 11),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-300l-0-12mc-c-50', '300L 0 12MC c 50', '112', 'Saco de Lixo 300L 0,12MC C/50', 12),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-300l-0-20-preto-c-50', '300L 0 20 Preto c 50', '113', 'Saco de Lixo 300L 0,20 Preto C/50', 13),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-300l-0-20mc-c-50', '300L 0 20MC c 50', '7805', 'Saco de Lixo 300L 0,20MC C/50', 14),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-40l-0-04-mc-preto-55x60cm-c-100', '40L 0 04 MC Preto 55X60CM c 100', '121', 'Saco de Lixo 40L 0,04 MC Preto 55X60CM C/100', 15),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-40l-reforcado-preto-55x60cm-c-100', '40L Reforcado Preto 55X60CM c 100', '8874', 'Saco de Lixo 40L Reforçado Preto 55X60CM C/100', 16),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-60l-0-04-mc-preto-63x70cm-c-100', '60L 0 04 MC Preto 63X70CM c 100', '123', 'Saco de Lixo 60L 0,04 MC Preto 63X70CM C/100', 17),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-60l-ref-preto-63x70cm', '60L REF Preto 63X70CM', '126', 'Saco de Lixo 60L Ref. Preto 63X70CM', 18),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-azul-100l-0-05mc-75x90cm', 'Azul 100L 0 05MC 75X90CM', '135', 'Saco de Lixo Azul 100L 0,05MC 75X90CM', 19),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-azul-100l-0-12', 'Azul 100L 0 12', '137', 'Saco de Lixo Azul 100L 0,12', 20),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-azul-200l-0-10mc', 'Azul 200L 0 10MC', '141', 'Saco de Lixo Azul 200L 0,10MC', 21),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-azul-200l-0-12-c-100', 'Azul 200L 0 12 c 100', '142', 'Saco de Lixo Azul 200L 0,12 C/100', 22),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-azul-20l-c-100', 'Azul 20L c 100', '6612', 'Saco de Lixo Azul 20L C/100', 23),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-azul-40l-brv', 'Azul 40L BRV', '146', 'Saco de Lixo Azul 40L BRV', 24),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-azul-60l', 'Azul 60L', '148', 'Saco de Lixo Azul 60L', 25),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-branco-100l-ref-0-08-c-100', 'Branco 100L REF 0 08 c 100', '5565', 'Saco de Lixo Branco 100L REF 0,08 C/100', 26),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-branco-20l-40x50cm-c-100', 'Branco 20L 40X50CM c 100', '150', 'Saco de Lixo Branco 20L 40X50CM C/100', 27),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-branco-40-l', 'Branco 40 L', '152', 'Saco de Lixo Branco 40 L', 28),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-branco-60l-c-100', 'Branco 60L c 100', '153', 'Saco de Lixo Branco 60L C/100', 29),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-hospitalar-100l-brv-reforcado-mc-0-6', 'Hospitalar 100L BRV Reforcado MC 0 6', '5514', 'Saco de Lixo Hospitalar 100L BRV Reforçado MC 0,6', 30),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-hospitalar-30l', 'Hospitalar 30L', '163', 'Saco de Lixo Hospitalar 30L', 31),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-hospitalar-brv-30l', 'Hospitalar BRV 30L', '5512', 'Saco de Lixo Hospitalar BRV 30L', 32),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-hospitalar-brv-50l', 'Hospitalar BRV 50L', '5513', 'Saco de Lixo Hospitalar BRV 50L', 33),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-laranja-100l-0-10-c-100', 'Laranja 100L 0 10 c 100', '5564', 'Saco de Lixo Laranja 100L 0,10 C/100', 34),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-transparente-100l-05mc', 'Transparente 100L 05MC', '4377', 'Saco de Lixo Transparente 100L 05MC', 35),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-transparente-40l', 'Transparente 40L', '184', 'Saco de Lixo Transparente 40L', 36),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-transparente-60l-c-100un', 'Transparente 60L c 100UN', '3235', 'Saco de Lixo Transparente 60L C/100UN', 37),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'saco-de-lixo-verde-60l-c-100', 'Verde 60L c 100', '192', 'Saco de Lixo Verde 60L C/100', 38),
  ('suporte-rolao-crem-600m-trilha-branco', 'suporte-rolao-crem-600m-trilha-branco', 'Branco', '4425', 'Suporte Rolao Crem 600M Trilha Branco', 1),
  ('suporte-rolao-crem-600m-trilha-branco', 'suporte-rolao-crem-600m-trilha-preto', 'Preto', '4344', 'Suporte Rolao Crem 600M Trilha Preto', 2),
  ('vassoura-novica-original-sem-cabo', 'vassoura-novica-original-sem-cabo', 'SEM Cabo', '9936', 'Vassoura Novica Original SEM Cabo', 1),
  ('vassoura-novica-original-sem-cabo', 'vassoura-novica-original-com-cabo', 'com Cabo', '7815', 'Vassoura Novica Original com Cabo', 2),
  ('agua-perfumada-caszulo-bambu-orieltal-500ml', 'agua-perfumada-caszulo-bambu-orieltal-500ml', 'Bambu Orieltal', '9877', 'Agua Perfumada Caszulo Bambu Orieltal 500ML', 1),
  ('agua-perfumada-caszulo-bambu-orieltal-500ml', 'agua-perfumada-caszulo-fava-de-baunilha-500ml', 'Fava de Baunilha', '9878', 'Agua Perfumada Caszulo Fava de Baunilha 500ML', 2),
  ('alcool-acendedor-araras-5l-80', 'alcool-acendedor-araras-5l-80', 'Araras', '6693', 'Álcool Acendedor Araras 5L 80%', 1),
  ('alcool-acendedor-araras-5l-80', 'alcool-acendedor-vale-verde-sulmar-5l-80', 'Vale Verde / Sulmar', '4388', 'Álcool Acendedor Vale Verde / Sulmar 5L 80%', 2),
  ('alcool-liquido-70-1-l-araras', 'alcool-liquido-70-1-l-araras', '1L', '8869', 'Álcool Liquido 70% 1 L Araras', 1),
  ('alcool-liquido-70-1-l-araras', 'alcool-liquido-araras-5l-70', '5L', '8868', 'Álcool Liquido Araras 5L 70%', 2),
  ('alcool-liquido-70-1-l-vale-verde', 'alcool-liquido-70-1-l-vale-verde', '70%', '4374', 'Álcool Liquido 70% 1 L Vale Verde', 1),
  ('alcool-liquido-70-1-l-vale-verde', 'alcool-liquido-92-8-1-l-vale-verde', '92,8%', '5579', 'Álcool Liquido 92,8% 1 L Vale Verde', 2),
  ('alcool-perfumado-floral-quimak-5l', 'alcool-perfumado-floral-quimak-5l', 'Floral', '6621', 'Álcool Perfumado Floral Quimak 5L', 1),
  ('alcool-perfumado-floral-quimak-5l', 'alcool-perfumado-lavanda-quimak-5l', 'Lavanda', '5519', 'Álcool Perfumado Lavanda Quimak 5L', 2)
  ) as v(parent_slug, member_slug, variant_name, code, original_name, sort_order)
)
insert into public.product_variants (product_id, name, code, price_label, description, active, sort_order)
select
  parent.id,
  v.variant_name,
  nullif(v.code, ''),
  null,
  v.original_name,
  true,
  v.sort_order
from variant_source v
join public.products parent on parent.slug = v.parent_slug
where not exists (
  select 1
  from public.product_variants existing
  where existing.product_id = parent.id
    and (
      (nullif(v.code, '') is not null and existing.code = nullif(v.code, ''))
      or lower(existing.name) = lower(v.variant_name)
    )
);

with category_source as (
  select *
  from (values
  ('amaciante-zavaski-coco-5-l', 'produtos-de-limpeza', 1),
  ('aromatizante-asa-140ml-floral-matricaria', 'aromatizadores', 1),
  ('aromatizante-cheirudo-140ml-bamboo', 'aromatizadores', 1),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizadores', 1),
  ('bloco-sanitario-p-caixa-acoplada-lavanda-higie-plus', 'banheiro', 1),
  ('bloqueador-sanitario-canela-premisse', 'banheiro', 1),
  ('cabo-aluminio-c-rosca-sanches-1-40mt-estriado', 'equipamentos', 1),
  ('conjunto-mop-po-40cm-sanches', 'equipamentos', 1),
  ('copo-180ml-dudigo-promo-com-25tr-transparente', 'descartaveis', 1),
  ('copo-termico-brv-120ml-tira-c-25', 'descartaveis', 1),
  ('desinfetante-spry-concentrado-kaiaque-1-20', 'produtos-de-limpeza', 1),
  ('detergente-clorado-zavaski-1l', 'produtos-de-limpeza', 1),
  ('fixar-aromatizantes-1l-spray-black', 'diversos', 1),
  ('gel-adesivo-sanitario-sany-aplic-refil-lavanda-brv', 'diversos', 1),
  ('luva-longatex-ranhurada-g', 'descartaveis', 1),
  ('luva-latex-procedimento-bompack-g-c-100-c-po', 'descartaveis', 1),
  ('luva-nitrilica-preta-g-c-100-bompack', 'descartaveis', 1),
  ('luva-verniz-bompack-g-azul', 'descartaveis', 1),
  ('pano-multiuso-c-5un-vermelho-30x50cm', 'produtos-de-limpeza', 1),
  ('pano-novo-microfibra-50x70-azul', 'papeis-e-panos', 1),
  ('pano-de-chao-alv-40x70', 'papeis-e-panos', 1),
  ('papel-hig-fofinho-folha-simples-30mt-pct-c4rl', 'papeis-e-panos', 1),
  ('papel-hig-rolao-branco-bv-c-8', 'papeis-e-panos', 1),
  ('refil-mop-po-40-sanches', 'equipamentos', 1),
  ('refil-sabonete-liq-proteinas-do-leite-spray-400ml-trilha', 'banheiro', 1),
  ('refil-alcool-70-spray-400ml-trilha', 'produtos-de-limpeza', 1),
  ('rodo-aluminio-reforcado-sanches-40cm-c-cabo-aluminio-de-1-50-mt-rosca', 'equipamentos', 1),
  ('rodo-plastico-40cm-sanches', 'equipamentos', 1),
  ('sabonete-liquido-ameixa-dourada-coala-500ml-pump', 'banheiro', 1),
  ('sabonete-liq-premisse-algas-marinhas-5l', 'banheiro', 1),
  ('sabonete-liq-sebold-cha-branco-5l', 'banheiro', 1),
  ('saboneteira-trilha-crem-c-reserv-branco', 'banheiro', 1),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'diversos', 1),
  ('suporte-rolao-crem-600m-trilha-branco', 'equipamentos', 1),
  ('vassoura-novica-original-sem-cabo', 'equipamentos', 1),
  ('agua-perfumada-caszulo-bambu-orieltal-500ml', 'aromatizadores', 1),
  ('alcool-acendedor-araras-5l-80', 'produtos-de-limpeza', 1),
  ('alcool-liquido-70-1-l-araras', 'produtos-de-limpeza', 1),
  ('alcool-liquido-70-1-l-vale-verde', 'produtos-de-limpeza', 1),
  ('alcool-perfumado-floral-quimak-5l', 'produtos-de-limpeza', 1)
  ) as v(parent_slug, category_slug, sort_order)
),
category_rows as (
  select p.id as product_id, c.id as category_id, cs.sort_order
  from category_source cs
  join public.products p on p.slug = cs.parent_slug
  join public.categories c on c.slug = cs.category_slug
)
insert into public.product_categories (product_id, category_id, sort_order)
select product_id, category_id, sort_order
from category_rows
on conflict (product_id, category_id) do update set
  sort_order = excluded.sort_order;

with primary_category as (
  select distinct on (cs.parent_slug) cs.parent_slug, c.id as category_id
  from (
    values
  ('amaciante-zavaski-coco-5-l', 'produtos-de-limpeza', 1),
  ('aromatizante-asa-140ml-floral-matricaria', 'aromatizadores', 1),
  ('aromatizante-cheirudo-140ml-bamboo', 'aromatizadores', 1),
  ('aromatizante-coala-120ml-algas-marinhas', 'aromatizadores', 1),
  ('bloco-sanitario-p-caixa-acoplada-lavanda-higie-plus', 'banheiro', 1),
  ('bloqueador-sanitario-canela-premisse', 'banheiro', 1),
  ('cabo-aluminio-c-rosca-sanches-1-40mt-estriado', 'equipamentos', 1),
  ('conjunto-mop-po-40cm-sanches', 'equipamentos', 1),
  ('copo-180ml-dudigo-promo-com-25tr-transparente', 'descartaveis', 1),
  ('copo-termico-brv-120ml-tira-c-25', 'descartaveis', 1),
  ('desinfetante-spry-concentrado-kaiaque-1-20', 'produtos-de-limpeza', 1),
  ('detergente-clorado-zavaski-1l', 'produtos-de-limpeza', 1),
  ('fixar-aromatizantes-1l-spray-black', 'diversos', 1),
  ('gel-adesivo-sanitario-sany-aplic-refil-lavanda-brv', 'diversos', 1),
  ('luva-longatex-ranhurada-g', 'descartaveis', 1),
  ('luva-latex-procedimento-bompack-g-c-100-c-po', 'descartaveis', 1),
  ('luva-nitrilica-preta-g-c-100-bompack', 'descartaveis', 1),
  ('luva-verniz-bompack-g-azul', 'descartaveis', 1),
  ('pano-multiuso-c-5un-vermelho-30x50cm', 'produtos-de-limpeza', 1),
  ('pano-novo-microfibra-50x70-azul', 'papeis-e-panos', 1),
  ('pano-de-chao-alv-40x70', 'papeis-e-panos', 1),
  ('papel-hig-fofinho-folha-simples-30mt-pct-c4rl', 'papeis-e-panos', 1),
  ('papel-hig-rolao-branco-bv-c-8', 'papeis-e-panos', 1),
  ('refil-mop-po-40-sanches', 'equipamentos', 1),
  ('refil-sabonete-liq-proteinas-do-leite-spray-400ml-trilha', 'banheiro', 1),
  ('refil-alcool-70-spray-400ml-trilha', 'produtos-de-limpeza', 1),
  ('rodo-aluminio-reforcado-sanches-40cm-c-cabo-aluminio-de-1-50-mt-rosca', 'equipamentos', 1),
  ('rodo-plastico-40cm-sanches', 'equipamentos', 1),
  ('sabonete-liquido-ameixa-dourada-coala-500ml-pump', 'banheiro', 1),
  ('sabonete-liq-premisse-algas-marinhas-5l', 'banheiro', 1),
  ('sabonete-liq-sebold-cha-branco-5l', 'banheiro', 1),
  ('saboneteira-trilha-crem-c-reserv-branco', 'banheiro', 1),
  ('sacos-de-lixo-de-todas-micras-tamanhos-e-cores', 'diversos', 1),
  ('suporte-rolao-crem-600m-trilha-branco', 'equipamentos', 1),
  ('vassoura-novica-original-sem-cabo', 'equipamentos', 1),
  ('agua-perfumada-caszulo-bambu-orieltal-500ml', 'aromatizadores', 1),
  ('alcool-acendedor-araras-5l-80', 'produtos-de-limpeza', 1),
  ('alcool-liquido-70-1-l-araras', 'produtos-de-limpeza', 1),
  ('alcool-liquido-70-1-l-vale-verde', 'produtos-de-limpeza', 1),
  ('alcool-perfumado-floral-quimak-5l', 'produtos-de-limpeza', 1)
  ) as cs(parent_slug, category_slug, sort_order)
  join public.categories c on c.slug = cs.category_slug
  order by cs.parent_slug, cs.sort_order
)
update public.products p
set category_id = pc.category_id
from primary_category pc
where p.slug = pc.parent_slug;

delete from public.products
where slug in (
  select slug
  from (values
  ('agua-perfumada-caszulo-fava-de-baunilha-500ml'),
  ('alcool-acendedor-vale-verde-sulmar-5l-80'),
  ('alcool-liquido-92-8-1-l-vale-verde'),
  ('alcool-liquido-araras-5l-70'),
  ('alcool-perfumado-lavanda-quimak-5l'),
  ('amaciante-zavaski-lavanda-5-l'),
  ('aromatizante-asa-140ml-laranja-c-canela'),
  ('aromatizante-cheirudo-140ml-lavanda'),
  ('aromatizante-cheirudo-140ml-talco'),
  ('aromatizante-coala-120ml-algodao'),
  ('aromatizante-coala-120ml-bambu'),
  ('aromatizante-coala-120ml-cha-branco'),
  ('aromatizante-coala-120ml-cravo-e-canela'),
  ('aromatizante-coala-120ml-eucalipto'),
  ('aromatizante-coala-120ml-lavanda'),
  ('aromatizante-coala-120ml-lima-limao'),
  ('aromatizante-coala-120ml-orquidea-negra'),
  ('aromatizante-coala-120ml-pinho'),
  ('aromatizante-coala-120ml-talco'),
  ('bloco-sanitario-p-caixa-acoplada-marine-higie-plus'),
  ('bloqueador-sanitario-capim-limao-premisse'),
  ('bloqueador-sanitario-tutti-frutti-premisse'),
  ('cabo-aluminio-c-rosca-sanches-1-40mt-liso'),
  ('conjunto-mop-po-60cm-sanches'),
  ('copo-180ml-dudigo-tr-c-100-transparente'),
  ('copo-180ml-gpack-com-25tr-transparente'),
  ('copo-180ml-gpack-glight-com-25tr-transparente'),
  ('copo-termico-brv-180ml-tira-c-25'),
  ('desinfetante-spry-concentrado-lavanda-1-20'),
  ('desinfetante-spry-concentrado-marine-1-20'),
  ('desinfetante-spry-concentrado-talco-1-20'),
  ('detergente-clorado-zavaski-5l'),
  ('fixar-aromatizantes-1l-spray-vanilla'),
  ('gel-adesivo-sanitario-sany-aplic-refil-marine-brv'),
  ('luva-latex-procedimento-bompack-m-c-100-c-po'),
  ('luva-latex-procedimento-bompack-p-c-100-c-po'),
  ('luva-latex-procedimento-bompack-pp-c-100-c-po'),
  ('luva-longatex-ranhurada-m'),
  ('luva-nitrilica-preta-g-g-c-100-bompack'),
  ('luva-nitrilica-preta-m-c-100-bompack'),
  ('luva-nitrilica-preta-p-c-100-bompack'),
  ('luva-verniz-bompack-m-azul'),
  ('luva-verniz-bompack-p-azul'),
  ('pano-de-chao-saco-economico-35x60-liso'),
  ('pano-de-chao-xadrez-extra-40x70'),
  ('pano-multiuso-rolo-30x30m-azul-rende-50-panos'),
  ('pano-multiuso-rolo-30x30m-verde-rende-50-panos'),
  ('pano-multiuso-rolo-bompack-azul-rende-600panos'),
  ('pano-novo-microfibra-50x70-verde'),
  ('pano-novo-microfibra-azul-peq-39x39cm'),
  ('pano-novo-microfibra-grande-39x59cm-azul'),
  ('pano-novo-microfibra-verde-peq-39x39cm'),
  ('papel-hig-30m-f-dupla-fofinho-pc-c-04rolos'),
  ('papel-hig-30m-fofinho-f-dupla-pc-c-12-rolos'),
  ('papel-hig-60m-f-simples-fofinho-pc-c-04-rolos'),
  ('papel-hig-rolao-extra-luxo-bv-fd-c-8-rolos-300mt'),
  ('papel-hig-rolao-folha-dupla-ipel-200mt-8-rolos'),
  ('papel-hig-rolao-plus-bv-c-8'),
  ('refil-alcool-70-spray-800ml-trilha'),
  ('refil-mop-po-60-sanches'),
  ('refil-mop-po-80-sanches'),
  ('refil-sabonete-liq-proteinas-do-leite-spray-800ml-trilha'),
  ('rodo-aluminio-reforcado-sanches-60cm-c-cabo-aluminio-1-50-mt-rosca'),
  ('rodo-plastico-60cm-sanches'),
  ('sabonete-liq-premisse-morango-e-champagne-5l'),
  ('sabonete-liq-sebold-erva-doce-5l'),
  ('sabonete-liq-sebold-pessego-5l'),
  ('sabonete-liquido-flor-de-figo-coala-500ml-pump'),
  ('sabonete-liquido-orquidea-negra-coala-500ml-pump'),
  ('saboneteira-trilha-crem-c-reserv-preto'),
  ('saco-de-lixo-100l-0-20mc-preto-pc-c-50un'),
  ('saco-de-lixo-100l-0-5-mc-preto-75x90cm-c-100'),
  ('saco-de-lixo-100l-ref-0-10-mc-preto-c-100'),
  ('saco-de-lixo-100l-ref-0-12-mc-preto-c-100'),
  ('saco-de-lixo-100l-ref-0-8-mc-preto-c-100'),
  ('saco-de-lixo-150l-ref-0-10mc-90x105cm-c-100'),
  ('saco-de-lixo-150l-ref-0-12-mc-preto-c-100'),
  ('saco-de-lixo-200l-0-12-preto-c-100'),
  ('saco-de-lixo-200l-0-20-c-50'),
  ('saco-de-lixo-20l-0-04-mc-preto-40x50cm-c-100'),
  ('saco-de-lixo-20l-ref-mc-preto-40x50cm-c-100'),
  ('saco-de-lixo-300l-0-12mc-c-50'),
  ('saco-de-lixo-300l-0-20-preto-c-50'),
  ('saco-de-lixo-300l-0-20mc-c-50'),
  ('saco-de-lixo-40l-0-04-mc-preto-55x60cm-c-100'),
  ('saco-de-lixo-40l-reforcado-preto-55x60cm-c-100'),
  ('saco-de-lixo-60l-0-04-mc-preto-63x70cm-c-100'),
  ('saco-de-lixo-60l-ref-preto-63x70cm'),
  ('saco-de-lixo-azul-100l-0-05mc-75x90cm'),
  ('saco-de-lixo-azul-100l-0-12'),
  ('saco-de-lixo-azul-200l-0-10mc'),
  ('saco-de-lixo-azul-200l-0-12-c-100'),
  ('saco-de-lixo-azul-20l-c-100'),
  ('saco-de-lixo-azul-40l-brv'),
  ('saco-de-lixo-azul-60l'),
  ('saco-de-lixo-branco-100l-ref-0-08-c-100'),
  ('saco-de-lixo-branco-20l-40x50cm-c-100'),
  ('saco-de-lixo-branco-40-l'),
  ('saco-de-lixo-branco-60l-c-100'),
  ('saco-de-lixo-hospitalar-100l-brv-reforcado-mc-0-6'),
  ('saco-de-lixo-hospitalar-30l'),
  ('saco-de-lixo-hospitalar-brv-30l'),
  ('saco-de-lixo-hospitalar-brv-50l'),
  ('saco-de-lixo-laranja-100l-0-10-c-100'),
  ('saco-de-lixo-transparente-100l-05mc'),
  ('saco-de-lixo-transparente-40l'),
  ('saco-de-lixo-transparente-60l-c-100un'),
  ('saco-de-lixo-verde-60l-c-100'),
  ('suporte-rolao-crem-600m-trilha-preto'),
  ('vassoura-novica-original-com-cabo')
  ) as v(slug)
);

commit;
